FROM registry.cn-qingdao.aliyuncs.com/dataease/sqlbot-base:latest AS sqlbot-ui-builder

ENV SQLBOT_HOME=/opt/sqlbot
ENV UI_HOME=${SQLBOT_HOME}/frontend
ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir -p ${UI_HOME}

COPY frontend /tmp/frontend
RUN cd /tmp/frontend && npm install && npm run build && mv dist ${UI_HOME}/dist


FROM registry.cn-qingdao.aliyuncs.com/dataease/sqlbot:v1.6.0

ENV SQLBOT_HOME=/opt/sqlbot
ENV APP_HOME=${SQLBOT_HOME}/app
ENV UI_HOME=${SQLBOT_HOME}/frontend
ENV PYTHONPATH=${SQLBOT_HOME}/app
ENV PATH="${APP_HOME}/.venv/bin:$PATH"

WORKDIR ${APP_HOME}

COPY start.sh ${APP_HOME}/start.sh
COPY backend ${APP_HOME}
COPY --from=sqlbot-ui-builder ${UI_HOME}/dist ${UI_HOME}/dist
COPY g2-ssr/app.js ${SQLBOT_HOME}/g2-ssr/app.js
COPY g2-ssr/charts ${SQLBOT_HOME}/g2-ssr/charts

RUN uv pip install --python ${APP_HOME}/.venv/bin/python \
    "pyhive[hive_pure_sasl]>=0.7.0" \
    "thrift-sasl"

ENTRYPOINT ["sh", "start.sh"]
